[package]
name = "world_core_prelude"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
chunking.workspace = true
spatial.workspace = true
spatial_index.workspace = true
world_streaming.workspace = true

[lints]
workspace = true
