[workspace]
resolver = "3"
members = [
  "crates/runen_spatial",
  "crates/runen_spatial_demand",
  "crates/runen_spatial_streaming",
  "adapters/godot_world_streaming",
  "xtask",
]

default-members = [
  "crates/runen_spatial",
  "crates/runen_spatial_demand",
  "crates/runen_spatial_streaming",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
rust-version = "1.93.0"
license = "GPL-3.0-only"
repository = "https://github.com/dornglut/runen-spatial"
publish = false

[workspace.dependencies]
godot = "0.5.3"
runen-spatial = { path = "crates/runen_spatial" }
runen-spatial-demand = { path = "crates/runen_spatial_demand" }
runen-spatial-streaming = { path = "crates/runen_spatial_streaming" }
serde = { version = "1.0.228", features = ["derive"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
