[package]
name = "chunk_streaming_demo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
world_core_prelude = { path = "../../crates/world_core_prelude" }

[lints]
workspace = true
